camel:
  springboot:
    main-run-controller: true

# Example for a mysql datasource
spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
